--admin
CREATE USER app_admin IDENTIFIED BY Jennpateadmin150102#;
GRANT CREATE SESSION TO app_admin;
ALTER USER app_admin DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER app_admin TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACT to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACTOR to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON DIRECT to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON DIRECTOR to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENRE to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROVIDER to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON SHOW to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON SHOW_PROV to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON SUBSCRIPTION to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TRANSACTION to app_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER to app_admin;

GRANT GRANT ANY PRIVILEGE TO admin;
GRANT CREATE ANY TABLE TO admin;
GRANT DROP ANY TABLE TO admin;
GRANT ALTER ANY TABLE TO admin;

--Content_Manager user
CREATE USER content_manager IDENTIFIED BY Jennpatecm150102#;
GRANT CREATE SESSION TO Content_Manager;
ALTER USER Content_Manager DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER Content_Manager TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO Content_Manager;

GRANT SELECT, INSERT, UPDATE, DELETE ON Actor TO content_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Director TO content_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Show TO content_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Show_Prov TO content_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Direct TO content_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Type TO content_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Genre TO content_manager;
GRANT SELECT ON Provider TO content_manager;
GRANT SELECT ON Subscription TO content_manager;


--Subscription_Manager user
CREATE USER Subscription_Manager IDENTIFIED BY Jennpatesm150102#;
GRANT CREATE SESSION TO Subscription_Manager;
ALTER USER Subscription_Manager DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER Subscription_Manager TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO Subscription_Manager;

GRANT SELECT, INSERT, UPDATE, DELETE ON Provider TO subscription_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Subscription TO subscription_manager;
GRANT SELECT, INSERT, UPDATE, DELETE ON Type TO subscription_manager;
GRANT SELECT ON Show TO subscription_manager;
GRANT SELECT ON Show_Prov TO subscription_manager;


-- Transaction_Manager user
CREATE USER transaction_manager IDENTIFIED BY Jennpatetm150102#;
GRANT CREATE SESSION TO Transaction_Manager;
ALTER USER Transaction_Manager DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER Transaction_Manager TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO Transaction_Manager;

GRANT SELECT ON Transaction TO transaction_manager;
GRANT SELECT ON Subscription TO transaction_manager;
GRANT SELECT ON Show TO transaction_manager;
GRANT SELECT ON "USER" TO transaction_manager;


--User user
CREATE USER regular_user IDENTIFIED BY Jennpateuser150102#;
GRANT CREATE SESSION TO regular_user;
ALTER USER regular_user DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER regular_user TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO regular_user;

GRANT SELECT ON Show TO regular_user;
GRANT SELECT ON Director TO regular_user;
GRANT SELECT ON Actor TO regular_user;
GRANT SELECT ON Genre TO regular_user;
GRANT SELECT ON Type TO regular_user;
GRANT INSERT, UPDATE, DELETE ON Transaction TO regular_user;


-- Auditor user
CREATE USER auditor IDENTIFIED BY Jennpateauditor150102#;
GRANT CREATE SESSION TO auditor;
ALTER USER auditor DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER auditor TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACT to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON ACTOR to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON DIRECT to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON DIRECTOR to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENRE to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROVIDER to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON SHOW to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON SHOW_PROV to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON SUBSCRIPTION to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON TRANSACTION to auditor;
GRANT SELECT, INSERT, UPDATE, DELETE ON USER to auditor;
